kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-binding
  namespace: prometheus
subjects:
- kind: ServiceAccount
  name: system:serviceaccounts:prometheus
  namespace: prometheus
  apiGroup: ""
roleRef:
  kind: Role
  name: prometheus-cluster-role
  apiGroup: rbac.authorization.k8s.io
