apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: recommendationservice-prod
namePrefix: prod-
commonAnnotations:
  stand: PROD
  namespace: hipster-shop-prod
bases:
  - ../../base
