repositories:
- name: stable
  url: https://kubernetes.github.io/ingress-nginx

- name: jetstack
  url: https://charts.jetstack.io

- name: harbor
  url: https://helm.goharbor.io

releases:
- name: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  version: 1.41.3
  namespace: ingress-nginx

- name: cert-manager
  chart: jetstack/cert-manager
  version: 0.16.1
  namespace: cert-manager
  set:
    - installCRDs: true
  hooks:
    - events: ["presync"]
      command: "kubectl"
      args: ["label", "namespace", "cert-manager", "certmanager.k8s.io/disable-validation=true"]

- name: harbor
  namespace: harbor
  chart: harbor/harbor
  version: 1.1.2
  values:
    - ../harbor-values.yaml

