apiVersion: v1
kind: Pod
metadata:
  name: web-hw1
  labels:
    app: web
spec:
  containers:
    - name: web-hw1-v1
      image: polovina/hw1:latest
      volumeMounts:
      - name: app
        mountPath: "/app"
      ports:
        - containerPort: 8000
  initContainers:
    - name: init-web
      image: busybox:latest
      command: ['sh', '-c', 'wget -O-  https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
      - name: app
        mountPath: "/app"
  volumes:
  - name: app
    emptyDir: {}

